# Generated by Django 3.2.8 on 2021-11-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_connect",
            field=models.BooleanField(default=True),
        ),
    ]
