# Generated by Django 3.2.8 on 2021-11-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('fr', 'Français (beta)'), ('en', 'English')], default='en-us', max_length=10),
        ),
    ]
