# Generated by Django 3.2.8 on 2021-11-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_first_connect"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="mneomonic",
            new_name="mnemonic",
        ),
    ]
