# Generated by Django 3.2.8 on 2021-11-25 16:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_mneomonic_user_mnemonic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('fr-FR', 'Français (beta)'), ('en-US', 'English')], default='en-us', max_length=10)),
                ('theme', models.CharField(choices=[('DK', 'Dark'), ('LT', 'Light')], default='DK', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.usersettings'),
        ),
    ]
