# Generated by Django 3.2.8 on 2021-11-25 17:11

import chat.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211125_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name_plural': 'User Settings'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=chat.utils.functions.PathAndRename('users/avatar')),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
