# Generated by Django 3.2.8 on 2022-05-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='pubkey',
        ),
        migrations.AddField(
            model_name='user',
            name='pubkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
