# Generated by Django 3.2.8 on 2022-05-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220525_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pubkey',
            new_name='public_key',
        ),
    ]
