# Generated by Django 3.2.8 on 2021-11-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0004_auto_20211114_1754'),
        ('users', '0007_auto_20211125_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='collapsed_categories',
            field=models.ManyToManyField(blank=True, default=None, to='guilds.Category'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('fr-fr', 'Français (beta)'), ('en-us', 'English')], default='en-us', max_length=10),
        ),
    ]
