# Generated by Django 3.1.13 on 2021-08-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField()),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("channels", models.ManyToManyField(to="guilds.Channel")),
            ],
        ),
        migrations.AddField(
            model_name="guild",
            name="categories",
            field=models.ManyToManyField(to="guilds.Category"),
        ),
        migrations.AddField(
            model_name="guild",
            name="channels",
            field=models.ManyToManyField(to="guilds.Channel"),
        ),
    ]
