# Generated by Django 3.2.8 on 2021-11-09 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("guilds", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="bans",
            field=models.ManyToManyField(
                related_name="bans", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
