# Generated by Django 3.1.13 on 2021-08-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0002_auto_20210808_1427"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="channel",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="guild",
            name="categories",
            field=models.ManyToManyField(blank=True, to="guilds.Category"),
        ),
        migrations.AlterField(
            model_name="guild",
            name="channels",
            field=models.ManyToManyField(blank=True, to="guilds.Channel"),
        ),
    ]
