# Generated by Django 3.2.6 on 2021-08-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0007_alter_channel_last_message_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField()),
                ("file", models.FileField(upload_to="")),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="attachments",
            field=models.ManyToManyField(to="guilds.Attachment"),
        ),
    ]
