# Generated by Django 3.2.6 on 2021-08-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0008_auto_20210812_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, null=True, to="guilds.Attachment"
            ),
        ),
    ]
