# Generated by Django 3.2.6 on 2021-08-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0009_alter_message_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="guilds.Attachment"),
        ),
    ]
