# Generated by Django 3.2.6 on 2021-08-12 16:04

import chat.guilds.features.channels.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0010_alter_message_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                upload_to=chat.guilds.features.channels.utils.PathAndRename(
                    "/attachments"
                )
            ),
        ),
    ]
