# Generated by Django 3.2.6 on 2021-08-12 16:43

import chat.guilds.features.channels.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0011_alter_attachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel",
                to="guilds.channel",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                upload_to=chat.guilds.features.channels.utils.PathAndRename(
                    "attachments"
                )
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="messages",
            field=models.ManyToManyField(
                related_name="messages", to="guilds.Message"
            ),
        ),
    ]
