# Generated by Django 3.2.6 on 2021-09-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0012_auto_20210812_1643"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="next",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_message",
                to="guilds.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="prev",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prev_message",
                to="guilds.message",
            ),
        ),
    ]
