# Generated by Django 3.2.6 on 2021-09-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0013_auto_20210902_1658"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="message",
            name="next",
        ),
        migrations.RemoveField(
            model_name="message",
            name="prev",
        ),
    ]
