# Generated by Django 3.2.6 on 2021-09-06 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0014_auto_20210906_2135"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="next",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_message",
                to="guilds.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="previous",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_message",
                to="guilds.message",
            ),
        ),
    ]
