# Generated by Django 3.2.6 on 2021-09-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0015_auto_20210906_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='filename',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
