# Generated by Django 3.2.6 on 2021-09-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0016_attachment_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='same_next_author',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='same_previous_author',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
