# Generated by Django 3.2.8 on 2022-05-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='nonce',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
