# Generated by Django 3.2.8 on 2021-11-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0003_auto_20211114_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='guild',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='guilds.Category'),
        ),
    ]
