# Generated by Django 3.2.8 on 2022-02-15 17:07

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0004_auto_20211114_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='key',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=10, unique=True),
        ),
    ]
