# Generated by Django 3.2.8 on 2022-05-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0005_alter_invite_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guilds.category'),
        ),
    ]
